; Form Designer for Purebasic - 5.30
; Warning: this file uses a strict syntax, if you edit it, make sure to respect the Form Designer limitation or it won't be opened again.

;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

Global WindowSettings

Global GadgetPath, GadgetButtonAutodetect, GadgetButtonBrowse, GadgetFrame, GadgetRights, GadgetSettingsInfo, GadgetOpenPath, GadgetSaveSettings, GadgetCancelSettings, GadgetSettingsWindowLocation, GadgetSettingsAutomaticUpdate, GadgetFrame, GadgetFrame, GadgetSettingsLocale

Declare ResizeGadgetsWindowSettings()

Declare GadgetCloseSettings(EventType)
Declare GadgetSaveSettings(EventType)
Declare GadgetButtonOpenPath(EventType)
Declare GadgetButtonAutodetect(EventType)
Declare GadgetButtonBrowse(EventType)

Procedure OpenWindowSettings(x = 0, y = 0, width = 580, height = 240)
  WindowSettings = OpenWindow(#PB_Any, x, y, width, height, l("settings","title"), #PB_Window_SystemMenu | #PB_Window_Invisible | #PB_Window_ScreenCentered, WindowID(WindowMain))
  GadgetPath = StringGadget(#PB_Any, 20, 70, 430, 25, "[Train Fever Path]")
  GadgetButtonAutodetect = ButtonGadget(#PB_Any, 460, 30, 100, 30, l("settings","autodetect"))
  GadgetToolTip(GadgetButtonAutodetect, l("settings","autodetect_tip"))
  GadgetButtonBrowse = ButtonGadget(#PB_Any, 460, 70, 100, 25, l("settings","browse"))
  GadgetToolTip(GadgetButtonBrowse, l("settings","browse_tip"))
  GadgetFrame = FrameGadget(#PB_Any, 10, 10, 560, 135, l("settings","path"))
  GadgetRights = TextGadget(#PB_Any, 20, 105, 430, 30, "")
  GadgetSettingsInfo = TextGadget(#PB_Any, 20, 30, 430, 35, l("settings","text"))
  GadgetOpenPath = ButtonGadget(#PB_Any, 460, 105, 100, 30, l("settings","open"))
  GadgetToolTip(GadgetOpenPath, l("settings","open_tip"))
  GadgetSaveSettings = ButtonGadget(#PB_Any, 450, 210, 120, 25, l("settings","save"))
  GadgetToolTip(GadgetSaveSettings, l("settings","save_tip"))
  GadgetCancelSettings = ButtonGadget(#PB_Any, 320, 210, 120, 25, l("settings","cancel"))
  GadgetToolTip(GadgetCancelSettings, l("settings","cancel_tip"))
  GadgetSettingsWindowLocation = CheckBoxGadget(#PB_Any, 20, 170, 280, 25, l("settings","restore"))
  GadgetToolTip(GadgetSettingsWindowLocation, l("settings","restore_tip"))
  GadgetSettingsAutomaticUpdate = CheckBoxGadget(#PB_Any, 20, 200, 280, 25, l("settings","update"))
  GadgetToolTip(GadgetSettingsAutomaticUpdate, l("settings","update_tip"))
  GadgetFrame = FrameGadget(#PB_Any, 10, 150, 300, 80, l("settings","other"))
  GadgetFrame = FrameGadget(#PB_Any, 320, 150, 250, 50, l("settings","locale"))
  GadgetSettingsLocale = ComboBoxGadget(#PB_Any, 330, 170, 230, 25, #PB_ComboBox_Image)
EndProcedure

Procedure ResizeGadgetsWindowSettings()
  Protected FormWindowWidth, FormWindowHeight
  FormWindowWidth = WindowWidth(WindowSettings)
  FormWindowHeight = WindowHeight(WindowSettings)
  ResizeGadget(GadgetPath, 20, 70, FormWindowWidth - 150, 25)
  ResizeGadget(GadgetButtonAutodetect, FormWindowWidth - 120, 30, 100, 30)
  ResizeGadget(GadgetButtonBrowse, FormWindowWidth - 120, 70, 100, 25)
EndProcedure

Procedure WindowSettings_Events(event)
  Select event
    Case #PB_Event_SizeWindow
      ResizeGadgetsWindowSettings()
    Case #PB_Event_CloseWindow
      ProcedureReturn #False

    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect

    Case #PB_Event_Gadget
      Select EventGadget()
        Case GadgetButtonAutodetect
          GadgetButtonAutodetect(EventType())          
        Case GadgetButtonBrowse
          GadgetButtonBrowse(EventType())          
        Case GadgetOpenPath
          GadgetButtonOpenPath(EventType())          
        Case GadgetSaveSettings
          GadgetSaveSettings(EventType())          
        Case GadgetCancelSettings
          GadgetCloseSettings(EventType())          
      EndSelect
  EndSelect
  ProcedureReturn #True
EndProcedure

